name = "Abhishek Banerjee"

[photo]
url = "https://upload.wikimedia.org/wikipedia/commons/9/98/Abhishek_Banerjee.jpg"
attribution = "Da27007, CC0, via Wikimedia Commons"

[[tenures]]
office_id = "mp-ls-diamond-harbour"
start = "2024-06-04"
