name = "Anniyur Siva @ Sivashanmugam A"

[photo]
url = "https://www.assembly.tn.gov.in/16thassembly/members/147_AS.jpg"

[contacts]
address = "26, Bharathiyar Street, Anniyur, Vikravandi Taluk, Viluppuram"
wikipedia = "Anniyur_Siva"

[[tenures]]
office_id = "mla-vikravandi"
start = "2021-05-03"
