name = "Chandhirakumar V.C"

[photo]
url = "https://www.assembly.tn.gov.in/16thassembly/members/98a.jpg"

[contacts]
address = "No. 51 Kiramadai, 2nd Street, Soorampatti Post, Erode - 638 009"
wikipedia = "V._C._Chandhirakumar"

[[tenures]]
office_id = "mla-erode-east"
start = "2025-02-09"
