name = "M. K. Stalin ministry"

[photo]
url = "https://upload.wikimedia.org/wikipedia/commons/8/81/TamilNadu_Logo.svg"
attribution = "File:Emblem of Tamil Nadu.svg:User:NikNaksFile:Emblem of India.svg: Various(see file)File:Flag_of_India.svg: various (see file)Derivative work:Perumalism Chat 08:23, 19 July 2013 (UTC), Public domain, via Wikimedia Commons"

[contacts]
wikipedia = "M._K._Stalin_ministry"
wikidata = "Q106920492"

[[tenures]]
office_id = "comtn"
