name = "Durai Murugan"

[photo]
url = "https://cms.tn.gov.in/cms_migrated/document/ministers_list/duraimurugan_040.jpg"

[contacts]
wikipedia = "Durai_Murugan"

[[tenures]]
office_id = "mla-katpadi"
start = "2021-05-03"

[[tenures]]
office_id = "tnmfwr"
