name = "Rajya Sabha"

[photo]
url = "https://upload.wikimedia.org/wikipedia/commons/1/14/Rajyasabha.svg"
attribution = "Swapnil1101, Public domain, via Wikimedia Commons"

[[tenures]]
office_id = "rs"
start = "1952-04-03"
