name = "16th Tamil Nadu Assembly"

[photo]
url = "https://upload.wikimedia.org/wikipedia/commons/8/81/TamilNadu_Logo.svg"
attribution = "File:Emblem of Tamil Nadu.svg:User:NikNaksFile:Emblem of India.svg: Various(see file)File:Flag_of_India.svg: various (see file)Derivative work:Perumalism Chat 08:23, 19 July 2013 (UTC), Public domain, via Wikimedia Commons"

[contacts]
wikipedia = "16th_Tamil_Nadu_Assembly"

[[tenures]]
office_id = "tn-la"
start = "2021-05-07"
