name = "Hemant Savara"

[photo]
url = "https://upload.wikimedia.org/wikipedia/commons/6/69/Hemant_Soren_2024.jpg"
attribution = "Prime Minister's Office, India, GODL-India <https://data.gov.in/sites/default/files/Gazette_Notification_OGDL.pdf>, via Wikimedia Commons"

[contacts]
wikipedia = "Hemant_Savara"
wikidata = "Q13619621"

[[tenures]]
office_id = "cmojh"
start = "2019-12-29"

[[tenures]]
office_id = "mp-ls-palghar"
start = "2024-06-04"
