name = "Joseph Samuel"

[contacts]
wikipedia = "Joseph_Samuel_(politician)"
x = "josephsamuelmla"
facebook = "Josephsamuel.MLA"
instagram = "ambattur_joseph_samuel"

[[tenures]]
office_id = "mla-ambattur"
start = "2021-05-03"

[[tenures]]
office_id = "mottnla"
