name = "Kuniyil Kailashnathan"

[photo]
url = "https://upload.wikimedia.org/wikipedia/commons/d/d3/K._Kailashnathan_%28cropped%29.png"
attribution = "GODL-India <https://data.gov.in/sites/default/files/Gazette_Notification_OGDL.pdf>, via Wikimedia Commons"

[contacts]
wikipedia = "Kuniyil_Kailashnathan"
wikidata = "Q17180691"

[[tenures]]
office_id = "lgopy"
start = "2024-08-07"
