name = "P. Moorthy"

[photo]
url = "https://cms.tn.gov.in/cms_migrated/document/ministers_list/moorthy_189.jpg"

[contacts]
wikipedia = "P._Moorthy"

[[tenures]]
office_id = "mla-madurai-east"
start = "2021-05-03"

[[tenures]]
office_id = "tnmfctar"
