name = "Nagesh Bapurao Patil Ashtikar"

[photo]
url = "https://upload.wikimedia.org/wikipedia/en/9/91/Nagesh_Patil.jpeg"
attribution = ""

[[tenures]]
office_id = "mp-ls-hingoli"
start = "2024-06-04"
