name = "K. R. Narayanan"

[photo]
url = "https://upload.wikimedia.org/wikipedia/commons/d/de/The_official_portrait_of_Shri_Kocheril_Raman_Narayanan%2C_10th_President_of_the_Republic_of_India.png"
attribution = "Government of India, GODL-India <https://data.gov.in/sites/default/files/Gazette_Notification_OGDL.pdf>, via Wikimedia Commons"

[contacts]
wikipedia = "K._R._Narayanan"

[[tenures]]
office_id = "poi"
start = "1997-07-25"
end = "2002-07-25"
