name = "Palanivel Thiaga Rajan"

[photo]
url = "https://upload.wikimedia.org/wikipedia/commons/b/b5/PTR.Thiagarajan.JPG"

[contacts]
wikipedia = "Palanivel_Thiagarajan"

[[tenures]]
office_id = "mla-madurai-central"
start = "2021-05-03"

[[tenures]]
office_id = "tnmfitads"
