name = "Praful Khoda Patel"

[photo]
url = "https://upload.wikimedia.org/wikipedia/commons/1/1b/Shri_Praful_Khoda_Patel.jpg"
attribution = "GODL-India <https://data.gov.in/sites/default/files/Gazette_Notification_OGDL.pdf>, via Wikimedia Commons"

[contacts]
wikipedia = "Praful_Khoda_Patel"
wikidata = "Q7237573"

[[tenures]]
office_id = "aodh"
start = "2020-01-26"

[[tenures]]
office_id = "aold"
start = "2020-12-05"
