name = "Pranab Mukherjee"

[photo]
url = "https://upload.wikimedia.org/wikipedia/commons/a/a9/Pranab_Mukherjee_Portrait_%28cropped%29.jpg"
attribution = "President's Secretariat (GODL-India), GODL-India <https://data.gov.in/sites/default/files/Gazette_Notification_OGDL.pdf>, via Wikimedia Commons"

[contacts]
wikipedia = "Pranab_Mukherjee"
wikidata = "Q57476"

[[tenures]]
office_id = "poi"
start = "2012-07-25"
end = "2017-07-25"
