name = "K. Radhakrishnan"

[photo]
url = "https://upload.wikimedia.org/wikipedia/commons/1/1c/Radakrishnan.jpeg"
attribution = "Fotokannan, CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons"

[[tenures]]
office_id = "mp-ls-alathur"
start = "2024-06-04"
