name = "R. Rajendran"

[photo]
url = "https://upload.wikimedia.org/wikipedia/commons/9/98/R_Rajendran.png"

[contacts]
wikipedia = "R._Rajendran"

[[tenures]]
office_id = "mla-salem-north"
start = "2021-05-03"

[[tenures]]
office_id = "tnmft"
