name = "Rajnath Singh"

[photo]
url = "https://upload.wikimedia.org/wikipedia/commons/d/d2/Rajnath.jpg"

[contacts]
website = "https://www.rajnathsingh.in/"
wikipedia = "Rajnath_Singh"

[[tenures]]
office_id = "cm"

[[tenures]]
office_id = "mp-ls-lucknow"
start = "2024-06-04"
