name = "Sanjay Jaiswal"

[photo]
url = "https://upload.wikimedia.org/wikipedia/commons/d/d7/Sanjay_Jaiswal_Member_of_Parliament_%28cropped%29.jpg"
attribution = "Information and public relations department Government of Bihar, Attribution, via Wikimedia Commons"

[[tenures]]
office_id = "mp-ls-paschim-champaran"
start = "2024-06-04"
