name = "P.K. Sekarbabu"

[photo]
url = "https://cms.tn.gov.in/cms_migrated/document/ministers_list/sekarbabu_018.jpg"

[contacts]
wikipedia = "P._K._Sekar_Babu"

[[tenures]]
office_id = "mla-harbour"
start = "2021-05-03"

[[tenures]]
office_id = "tnmfhrace"
