name = "Shivraj Singh Chauhan"

[photo]
url = "https://upload.wikimedia.org/wikipedia/commons/c/c0/Shivraj_Singh_Chouhan_%28Cropped_3%29.jpg"

[contacts]
wikipedia = "Shivraj_Singh_Chauhan"
wikidata = "Q3180602"

[[tenures]]
office_id = "cmomp"
start = "2020-03-23"

[[tenures]]
office_id = "mp-ls-vidisha"
start = "2024-06-04"
