name = "M. K. Stalin"

[photo]
url = "https://upload.wikimedia.org/wikipedia/commons/9/9d/The_Chief_Minister_of_Tamil_Nadu%2C_Thiru_MK_Stalin.jpg"
attribution = "Prime Minister's Office (GODL-India), GODL-India <https://data.gov.in/sites/default/files/Gazette_Notification_OGDL.pdf>, via Wikimedia Commons"

[contacts]
website = "http://mkstalin.in/"
wikipedia = "M._K._Stalin"
wikidata = "Q983475"

[[tenures]]
office_id = "cmotn"
start = "2021-05-07"
